# Ardhinata's custom aria2 config

check-integrity=true
continue=true
#lowest-speed-limit=8K
max-concurrent-downloads=16
max-connection-per-server=8
min-split-size=1M
split=16
stream-piece-selector=random
check-certificate=false
http-no-cache=true
enable-http-pipelining=true
#console-log-level=info
file-allocation=falloc
event-poll=epoll
optimize-concurrent-downloads=true
download-result=full
disk-cache=4096M
rpc-secret=d59ae74c4131d54eadba69e2b3f8c16046648f6d
