# ~/.zshrc
source ~/.antigen.zsh

antigen use oh-my-zsh
antigen bundles < ~/.antigen-bundles.txt

antigen theme fishy
antigen apply

source ~/.zsh_useropts.zsh
# The following lines were added by compinstall
zstyle :compinstall filename '/home/ardhinata/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
